// -------------------------------------------------------------------------
/**
 * Test class for personal testing of the SemSearch class.
 * 
 * This test class includes various test cases to verify the functionality
 * of the SemSearch system by simulating different command inputs, including
 * valid operations, edge cases, and error handling scenarios.
 * 
 * The tests cover inserting, deleting, and searching for Seminar objects in
 * the SemSearch database, along with error handling for invalid inputs.
 * 
 * @see SemSearch
 * @see Seminar
 * @see CommandProcessor
 * 
 * @author markz + tarinid
 * @version Oct 7, 2024
 */
public class ReferenceTest extends student.TestCase {
    // ----------------------------------------------------------
    /**
     * Setup for tests.
     * 
     * This method is intentionally left empty as no initialization is required
     * before running the tests.
     */
    public void setUp() {
        // Empty on purpose
    }


    // ----------------------------------------------------------
    /**
     * Test the SemSearch system using the "TestInput.txt" command file.
     * 
     * This test verifies the correct functionality of the system by simulating
     * various operations such as deleting, inserting, searching for seminars
     * by ID, date, cost, keyword, and location, and printing the tree
     * structures.
     * 
     * It also checks for the correct error messages when invalid operations
     * are attempted, such as inserting seminars with invalid coordinates or
     * searching for nonexistent records.
     */
    public void testSemSearch() {
        String[] args = new String[2];
        args[0] = "128";
        args[1] = "TestInput.txt";

        SemSearch.main(args);

        assertFuzzyEquals("Delete FAILED -- There is no record with ID 1\n"
            + "ID Tree:\n" + "This tree is empty\n" + "Date Tree:\n"
            + "This tree is empty\n" + "Cost Tree:\n" + "This tree is empty\n"
            + "Keyword Tree:\n" + "This tree is empty\n" + "Location Tree:\n"
            + "E\n" + "Invalid field: :3\n"
            + "Search FAILED -- There is no record with ID 1\n"
            + "Seminars with dates in range 0 to 1:\n"
            + "1 nodes visited in this search\n"
            + "Seminars with costs in range 0 to 1:\n"
            + "1 nodes visited in this search\n"
            + "Seminars matching keyword VT:\n"
            + "Seminars within 0 units of 0, 0:\n"
            + "1 nodes visited in this search\n" + "Invalid keyword\n"
            + "Insert FAILED - Bad x, y coordinates: -1, -1\n"
            + "Insert FAILED - Bad x, y coordinates: -1, 129\n"
            + "Insert FAILED - Bad x, y coordinates: 129, 129\n"
            + "Insert FAILED - Bad x, y coordinates: -1, 0\n"
            + "Insert FAILED - Bad x, y coordinates: 0, -1\n"
            + "Insert FAILED - Bad x, y coordinates: 128, 129\n"
            + "Successfully inserted record with ID 1\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Insert FAILED - There is already a record with ID 1\n"
            + "ID Tree:\n" + "(null)\n" + "    \\\n" + "    (1)\n" + "    /\n"
            + "(null)\n" + "Number of records: 1\n" + "Date Tree:\n"
            + "(null)\n" + "    \\\n" + "    (0610051600)\n" + "    /\n"
            + "(null)\n" + "Number of records: 1\n" + "Cost Tree:\n"
            + "(null)\n" + "    \\\n" + "    (50)\n" + "    /\n" + "(null)\n"
            + "Number of records: 1\n" + "Keyword Tree:\n" + "        (null)\n"
            + "            \\\n" + "            (key1)\n" + "            /\n"
            + "    (null)\n" + "        \\\n" + "        (key2)\n"
            + "        /\n" + "(null)\n" + "    \\\n" + "    (key3)\n"
            + "    /\n" + "(null)\n" + "Number of records: 3\n"
            + "Location Tree:\n" + "(Leaf with 1 objects: 1)\n"
            + "Found record with ID 1:\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Seminars with dates in range 0 to 1:\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "3 nodes visited in this search\n"
            + "Seminars with costs in range 0 to 1:\n"
            + "2 nodes visited in this search\n"
            + "Seminars matching keyword VT:\n"
            + "Seminars within 20 units of 0, 0:\n"
            + "Found a record with key value 1 at 10, 10\n"
            + "1 nodes visited in this search\n"
            + "Record with ID 1 successfully deleted from the database\n"
            + "Successfully inserted record with ID 1\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 2\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n" + "ID Tree:\n" + "    (null)\n"
            + "        \\\n" + "        (1)\n" + "        /\n" + "(null)\n"
            + "    \\\n" + "    (2)\n" + "    /\n" + "(null)\n"
            + "Number of records: 2\n" + "Date Tree:\n" + "(null)\n"
            + "    \\\n" + "    (0610051600)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (0610051600)\n" + "        /\n"
            + "    (null)\n" + "Number of records: 2\n" + "Cost Tree:\n"
            + "(null)\n" + "    \\\n" + "    (50)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (50)\n" + "        /\n" + "    (null)\n"
            + "Number of records: 2\n" + "Keyword Tree:\n" + "        (null)\n"
            + "            \\\n" + "            (key1)\n" + "            /\n"
            + "        (null)\n" + "                \\\n"
            + "                (key1)\n" + "                /\n"
            + "    (null)\n" + "        \\\n" + "        (key2)\n"
            + "        /\n" + "    (null)\n" + "            \\\n"
            + "            (key2)\n" + "            /\n" + "(null)\n"
            + "    \\\n" + "    (key3)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (key3)\n" + "        /\n"
            + "    (null)\n" + "Number of records: 6\n" + "Location Tree:\n"
            + "(Leaf with 2 objects: 1 2)\n" + "Found record with ID 1:\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Seminars with dates in range 0 to 1:\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "5 nodes visited in this search\n"
            + "Seminars with costs in range 0 to 100:\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "5 nodes visited in this search\n"
            + "Seminars matching keyword key1:\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Seminars within 20 units of 0, 0:\n"
            + "Found a record with key value 1 at 10, 10\n"
            + "Found a record with key value 2 at 10, 10\n"
            + "1 nodes visited in this search\n"
            + "Record with ID 1 successfully deleted from the database\n"
            + "Record with ID 2 successfully deleted from the database\n"
            + "Successfully inserted record with ID 2\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 1\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 3\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID Tree:\n" + "(null)\n"
            + "    \\\n" + "    (1)\n" + "    /\n" + "(null)\n" + "        \\\n"
            + "        (2)\n" + "        /\n" + "(null)\n" + "    \\\n"
            + "    (3)\n" + "    /\n" + "(null)\n" + "Number of records: 3\n"
            + "Date Tree:\n" + "(null)\n" + "    \\\n" + "    (0610051600)\n"
            + "    /\n" + "(null)\n" + "        \\\n" + "        (0610051600)\n"
            + "        /\n" + "    (null)\n" + "            \\\n"
            + "            (0610051600)\n" + "            /\n"
            + "        (null)\n" + "Number of records: 3\n" + "Cost Tree:\n"
            + "(null)\n" + "    \\\n" + "    (50)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (50)\n" + "        /\n" + "    (null)\n"
            + "            \\\n" + "            (50)\n" + "            /\n"
            + "        (null)\n" + "Number of records: 3\n" + "Keyword Tree:\n"
            + "        (null)\n" + "            \\\n" + "            (key1)\n"
            + "            /\n" + "        (null)\n" + "                \\\n"
            + "                (key1)\n" + "                /\n"
            + "            (null)\n" + "                    \\\n"
            + "                    (key1)\n" + "                    /\n"
            + "    (null)\n" + "        \\\n" + "        (key2)\n"
            + "        /\n" + "    (null)\n" + "            \\\n"
            + "            (key2)\n" + "            /\n" + "        (null)\n"
            + "                \\\n" + "                (key2)\n"
            + "                /\n" + "(null)\n" + "    \\\n" + "    (key3)\n"
            + "    /\n" + "(null)\n" + "        \\\n" + "        (key3)\n"
            + "        /\n" + "    (null)\n" + "            \\\n"
            + "            (key3)\n" + "            /\n" + "        (null)\n"
            + "Number of records: 9\n" + "Location Tree:\n"
            + "(Leaf with 3 objects: 1 2 3)\n" + "Found record with ID 1:\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Seminars with dates in range 0 to 1:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars with costs in range 0 to 100:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars matching keyword key1:\n" + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "Seminars within 20 units of 0, 0:\n"
            + "Found a record with key value 1 at 10, 10\n"
            + "Found a record with key value 2 at 10, 10\n"
            + "Found a record with key value 3 at 10, 10\n"
            + "1 nodes visited in this search\n"
            + "Seminars with dates in range 0610051600 to 0610051600:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "4 nodes visited in this search\n"
            + "Seminars with dates in range 0610051601 to 0610051601:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with dates in range 0610051599 to 0610051599:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with dates in range 0610051600 to 0610051601:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars with dates in range 0610051599 to 0610051600:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars with dates in range 0610051601 to 0610051602:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with dates in range 0610051598 to 0610051599:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with dates in range 0610051601 to 0610051600:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with dates in range 0610051600 to 0610051599:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with dates in range 0610051602 to 0610051601:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with dates in range 0610051599 to 0610051598:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with costs in range 50 to 50:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "4 nodes visited in this search\n"
            + "Seminars with costs in range 49 to 49:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with costs in range 51 to 51:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with costs in range 50 to 51:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars with costs in range 49 to 50:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "7 nodes visited in this search\n"
            + "Seminars with costs in range 51 to 52:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with costs in range 48 to 49:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with costs in range 51 to 50:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with costs in range 50 to 49:\n"
            + "4 nodes visited in this search\n"
            + "Seminars with costs in range 52 to 51:\n"
            + "2 nodes visited in this search\n"
            + "Seminars with costs in range 49 to 48:\n"
            + "4 nodes visited in this search\n"
            + "Successfully inserted record with ID 4\n"
            + "ID: 4, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 9, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 5\n"
            + "ID: 5, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 13, Y: 4, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 6\n"
            + "ID: 6, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 7, Y: 9, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "Location Tree:\n"
            + "                                            (I)\n"
            + "                                        (E)\n"
            + "                                        (I)\n"
            + "                                    (E)\n"
            + "                                    (I)\n"
            + "                                (E)\n"
            + "                                (I)\n"
            + "                            (E)\n"
            + "                            (I)\n"
            + "                        (E)\n" + "                        (I)\n"
            + "                    (E)\n" + "                    (I)\n"
            + "                (I)\n" + "            (I)\n" + "        (E)\n"
            + "        (I)\n" + "    (E)\n" + "    (I)\n"
            + "(Leaf with 3 objects: 1 2 3)\n" + "(Leaf with 1 objects: 4)\n"
            + "            (Leaf with 1 objects: 5)\n"
            + "                (Leaf with 1 objects: 6)\n"
            + "Record with ID 3 successfully deleted from the database\n"
            + "Location Tree:\n"
            + "                                            (I)\n"
            + "                                        (E)\n"
            + "                                        (I)\n"
            + "                                    (E)\n"
            + "                                    (I)\n"
            + "                                (E)\n"
            + "                                (I)\n"
            + "                            (E)\n"
            + "                            (I)\n"
            + "                        (E)\n" + "                        (I)\n"
            + "                    (E)\n" + "                    (I)\n"
            + "                (I)\n" + "            (I)\n" + "        (E)\n"
            + "        (I)\n" + "    (E)\n" + "    (I)\n"
            + "(Leaf with 2 objects: 1 2)\n" + "(Leaf with 1 objects: 4)\n"
            + "            (Leaf with 1 objects: 5)\n"
            + "                (Leaf with 1 objects: 6)\n"
            + "Seminars within 1 units of 0, 0:\n"
            + "8 nodes visited in this search\n"
            + "Seminars within 4 units of 0, 0:\n"
            + "8 nodes visited in this search\n"
            + "Seminars within 10 units of 0, 0:\n"
            + "15 nodes visited in this search\n"
            + "Seminars within 20 units of 0, 0:\n"
            + "Found a record with key value 6 at 7, 9\n"
            + "Found a record with key value 5 at 13, 4\n"
            + "Found a record with key value 4 at 9, 10\n"
            + "Found a record with key value 1 at 10, 10\n"
            + "Found a record with key value 2 at 10, 10\n"
            + "19 nodes visited in this search", systemOut().getHistory());
    }


    // ----------------------------------------------------------
    /**
     * Test the SemSearch system using the "TestInput2.txt" command file.
     * 
     * This test verifies the system's behavior with a different command file,
     * testing the correct insertion and deletion of seminar records and the
     * printing of various tree structures, ensuring that records are properly
     * inserted and removed.
     */
    public void testSemSearchWithTestInput2() {
        String[] args = new String[2];
        args[0] = "128";
        args[1] = "TestInput2";

        SemSearch.main(args);

        assertFuzzyEquals("Successfully inserted record with ID 1\n"
            + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 5, Y: 5, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 2\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 4, Y: 4, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 3\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 3, Y: 3, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 4\n"
            + "ID: 4, Title: Seminar 4\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 4\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 5\n"
            + "ID: 5, Title: Seminar 5\n"
            + "Date: 0610051600, Length: 100, X: 11, Y: 11, Cost: 50\n"
            + "Description: This is Seminar 5\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 6\n"
            + "ID: 6, Title: Seminar 6\n"
            + "Date: 0610051600, Length: 100, X: 12, Y: 12, Cost: 50\n"
            + "Description: This is Seminar 6\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 7\n"
            + "ID: 7, Title: Seminar 7\n"
            + "Date: 0610051600, Length: 100, X: 6, Y: 6, Cost: 50\n"
            + "Description: This is Seminar 7\n"
            + "Keywords: key1, key2, key3\n"
            + "Successfully inserted record with ID 8\n"
            + "ID: 8, Title: Seminar 8\n"
            + "Date: 0610051600, Length: 100, X: 9, Y: 9, Cost: 50\n"
            + "Description: This is Seminar 8\n"
            + "Keywords: key1, key2, key3\n" + "ID Tree:\n"
            + "                            (null)\n"
            + "                                \\\n"
            + "                                (1)\n"
            + "                                /\n"
            + "                        (null)\n"
            + "                            \\\n"
            + "                            (2)\n"
            + "                            /\n" + "                    (null)\n"
            + "                        \\\n" + "                        (3)\n"
            + "                        /\n" + "                (null)\n"
            + "                    \\\n" + "                    (4)\n"
            + "                    /\n" + "            (null)\n"
            + "                \\\n" + "                (5)\n"
            + "                /\n" + "        (null)\n" + "            \\\n"
            + "            (6)\n" + "            /\n" + "    (null)\n"
            + "        \\\n" + "        (7)\n" + "        /\n" + "(null)\n"
            + "    \\\n" + "    (8)\n" + "    /\n" + "(null)\n"
            + "Number of records: 8\n" + "Date Tree:\n" + "(null)\n"
            + "    \\\n" + "    (0610051600)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (0610051600)\n" + "        /\n"
            + "    (null)\n" + "            \\\n" + "            (0610051600)\n"
            + "            /\n" + "        (null)\n" + "                \\\n"
            + "                (0610051600)\n" + "                /\n"
            + "            (null)\n" + "                    \\\n"
            + "                    (0610051600)\n" + "                    /\n"
            + "                (null)\n" + "                        \\\n"
            + "                        (0610051600)\n"
            + "                        /\n" + "                    (null)\n"
            + "                            \\\n"
            + "                            (0610051600)\n"
            + "                            /\n"
            + "                        (null)\n"
            + "                                \\\n"
            + "                                (0610051600)\n"
            + "                                /\n"
            + "                            (null)\n" + "Number of records: 8\n"
            + "Cost Tree:\n" + "(null)\n" + "    \\\n" + "    (50)\n"
            + "    /\n" + "(null)\n" + "        \\\n" + "        (50)\n"
            + "        /\n" + "    (null)\n" + "            \\\n"
            + "            (50)\n" + "            /\n" + "        (null)\n"
            + "                \\\n" + "                (50)\n"
            + "                /\n" + "            (null)\n"
            + "                    \\\n" + "                    (50)\n"
            + "                    /\n" + "                (null)\n"
            + "                        \\\n" + "                        (50)\n"
            + "                        /\n" + "                    (null)\n"
            + "                            \\\n"
            + "                            (50)\n"
            + "                            /\n"
            + "                        (null)\n"
            + "                                \\\n"
            + "                                (50)\n"
            + "                                /\n"
            + "                            (null)\n" + "Number of records: 8\n"
            + "Keyword Tree:\n" + "        (null)\n" + "            \\\n"
            + "            (key1)\n" + "            /\n" + "        (null)\n"
            + "                \\\n" + "                (key1)\n"
            + "                /\n" + "            (null)\n"
            + "                    \\\n" + "                    (key1)\n"
            + "                    /\n" + "                (null)\n"
            + "                        \\\n"
            + "                        (key1)\n" + "                        /\n"
            + "                    (null)\n"
            + "                            \\\n"
            + "                            (key1)\n"
            + "                            /\n"
            + "                        (null)\n"
            + "                                \\\n"
            + "                                (key1)\n"
            + "                                /\n"
            + "                            (null)\n"
            + "                                    \\\n"
            + "                                    (key1)\n"
            + "                                    /\n"
            + "                                (null)\n"
            + "                                        \\\n"
            + "                                        (key1)\n"
            + "                                        /\n" + "    (null)\n"
            + "        \\\n" + "        (key2)\n" + "        /\n"
            + "    (null)\n" + "            \\\n" + "            (key2)\n"
            + "            /\n" + "        (null)\n" + "                \\\n"
            + "                (key2)\n" + "                /\n"
            + "            (null)\n" + "                    \\\n"
            + "                    (key2)\n" + "                    /\n"
            + "                (null)\n" + "                        \\\n"
            + "                        (key2)\n" + "                        /\n"
            + "                    (null)\n"
            + "                            \\\n"
            + "                            (key2)\n"
            + "                            /\n"
            + "                        (null)\n"
            + "                                \\\n"
            + "                                (key2)\n"
            + "                                /\n"
            + "                            (null)\n"
            + "                                    \\\n"
            + "                                    (key2)\n"
            + "                                    /\n" + "(null)\n"
            + "    \\\n" + "    (key3)\n" + "    /\n" + "(null)\n"
            + "        \\\n" + "        (key3)\n" + "        /\n"
            + "    (null)\n" + "            \\\n" + "            (key3)\n"
            + "            /\n" + "        (null)\n" + "                \\\n"
            + "                (key3)\n" + "                /\n"
            + "            (null)\n" + "                    \\\n"
            + "                    (key3)\n" + "                    /\n"
            + "                (null)\n" + "                        \\\n"
            + "                        (key3)\n" + "                        /\n"
            + "                    (null)\n"
            + "                            \\\n"
            + "                            (key3)\n"
            + "                            /\n"
            + "                        (null)\n"
            + "                                \\\n"
            + "                                (key3)\n"
            + "                                /\n"
            + "                            (null)\n" + "Number of records: 24\n"
            + "Location Tree:\n"
            + "                                                    (I)\n"
            + "                                                (E)\n"
            + "                                                (I)\n"
            + "                                            (E)\n"
            + "                                            (I)\n"
            + "                                        (E)\n"
            + "                                        (I)\n"
            + "                                    (E)\n"
            + "                                    (I)\n"
            + "                                (E)\n"
            + "                                (I)\n"
            + "                            (E)\n"
            + "                            (I)\n"
            + "                        (I)\n" + "                    (I)\n"
            + "                (Leaf with 1 objects: 6)\n"
            + "                (I)\n" + "            (E)\n"
            + "            (I)\n" + "        (I)\n" + "    (I)\n"
            + "(Leaf with 1 objects: 5)\n" + "(Leaf with 1 objects: 4)\n"
            + "    (E)\n" + "        (Leaf with 1 objects: 8)\n"
            + "                    (E)\n" + "                        (I)\n"
            + "                    (E)\n" + "                    (I)\n"
            + "                (I)\n" + "            (I)\n"
            + "        (Leaf with 1 objects: 7)\n" + "        (I)\n"
            + "    (E)\n" + "    (I)\n" + "(Leaf with 1 objects: 1)\n"
            + "(Leaf with 1 objects: 2)\n" + "            (E)\n"
            + "                (Leaf with 1 objects: 3)\n"
            + "Found record with ID 1:\n" + "ID: 1, Title: Seminar 1\n"
            + "Date: 0610051600, Length: 100, X: 5, Y: 5, Cost: 50\n"
            + "Description: This is Seminar 1\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 2:\n"
            + "ID: 2, Title: Seminar 2\n"
            + "Date: 0610051600, Length: 100, X: 4, Y: 4, Cost: 50\n"
            + "Description: This is Seminar 2\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 3:\n"
            + "ID: 3, Title: Seminar 3\n"
            + "Date: 0610051600, Length: 100, X: 3, Y: 3, Cost: 50\n"
            + "Description: This is Seminar 3\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 4:\n"
            + "ID: 4, Title: Seminar 4\n"
            + "Date: 0610051600, Length: 100, X: 10, Y: 10, Cost: 50\n"
            + "Description: This is Seminar 4\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 5:\n"
            + "ID: 5, Title: Seminar 5\n"
            + "Date: 0610051600, Length: 100, X: 11, Y: 11, Cost: 50\n"
            + "Description: This is Seminar 5\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 6:\n"
            + "ID: 6, Title: Seminar 6\n"
            + "Date: 0610051600, Length: 100, X: 12, Y: 12, Cost: 50\n"
            + "Description: This is Seminar 6\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 7:\n"
            + "ID: 7, Title: Seminar 7\n"
            + "Date: 0610051600, Length: 100, X: 6, Y: 6, Cost: 50\n"
            + "Description: This is Seminar 7\n"
            + "Keywords: key1, key2, key3\n" + "Found record with ID 8:\n"
            + "ID: 8, Title: Seminar 8\n"
            + "Date: 0610051600, Length: 100, X: 9, Y: 9, Cost: 50\n"
            + "Description: This is Seminar 8\n"
            + "Keywords: key1, key2, key3\n"
            + "Record with ID 1 successfully deleted from the database\n"
            + "Record with ID 4 successfully deleted from the database\n"
            + "Record with ID 2 successfully deleted from the database\n"
            + "Record with ID 5 successfully deleted from the database\n"
            + "Record with ID 3 successfully deleted from the database\n"
            + "Record with ID 6 successfully deleted from the database\n"
            + "ID Tree:\n" + "    (null)\n" + "        \\\n" + "        (7)\n"
            + "        /\n" + "(null)\n" + "    \\\n" + "    (8)\n" + "    /\n"
            + "(null)\n" + "Number of records: 2\n" + "Date Tree:\n"
            + "(null)\n" + "    \\\n" + "    (0610051600)\n" + "    /\n"
            + "(null)\n" + "        \\\n" + "        (0610051600)\n"
            + "        /\n" + "    (null)\n" + "Number of records: 2\n"
            + "Cost Tree:\n" + "(null)\n" + "    \\\n" + "    (50)\n"
            + "    /\n" + "(null)\n" + "        \\\n" + "        (50)\n"
            + "        /\n" + "    (null)\n" + "Number of records: 2\n"
            + "Keyword Tree:\n" + "This tree is empty\n" + "Location Tree:\n"
            + "                            (I)\n"
            + "                        (E)\n" + "                        (I)\n"
            + "                    (E)\n" + "                    (I)\n"
            + "                (E)\n" + "                (I)\n"
            + "            (E)\n" + "            (I)\n" + "        (E)\n"
            + "        (I)\n" + "    (E)\n" + "    (I)\n"
            + "(Leaf with 1 objects: 8)\n" + "(Leaf with 1 objects: 7)\n"
            + "Search FAILED -- There is no record with ID 1\n"
            + "Search FAILED -- There is no record with ID 2\n"
            + "Search FAILED -- There is no record with ID 3\n"
            + "Search FAILED -- There is no record with ID 4\n"
            + "Search FAILED -- There is no record with ID 5\n"
            + "Search FAILED -- There is no record with ID 6", systemOut()
                .getHistory());
    }


    // ----------------------------------------------------------
    /**
     * Test error handling in SemSearch.
     * 
     * This test verifies that the system handles errors gracefully by
     * simulating
     * incorrect inputs, such as invalid world size values, null command files,
     * or incomplete argument arrays, and ensures that appropriate error
     * messages are displayed.
     */
    public void testError() {
        String[] args = new String[2];
        args[0] = "a";
        args[1] = "TestInput";

        SemSearch.main(args);

        args[0] = "2";
        args[1] = null;

        SemSearch.main(args);

        args = null;
        SemSearch.main(args);

        args = new String[1];
        SemSearch.main(args);

        fuzzyEquals(
            "Invalid number format for worldSize. "
            + "Please provide an integer.\r\n"
                + "An error occurred: null\r\n"
                + "java.lang.NullPointerException\r\n"
                + "    at java.base/java.io.File.<init>"
                + "(File.java:276)\r\n"
                + "    at CommandProcessor.<init>"
                + "(CommandProcessor.java:30)\r\n"
                + "    at SemSearch.main(SemSearch.java:68)\r\n"
                + "    at ReferenceTest.testError"
                + "(ReferenceTest.java:85)\r\n"
                + "    at java.base/jdk.internal."
                + "reflect.NativeMethodAccessorImpl.invoke0"
                + "(Native Method)\r\n"
                + "    at java.base/jdk.internal."
                + "reflect.NativeMethodAccessorImpl.invoke(Native"
                + "MethodAccessorImpl.java:62)\r\n"
                + "    at java.base/jdk.internal."
                + "reflect.DelegatingMethodAccessorImpl.invoke"
                + "(DelegatingMethodAccessorImpl.java:43)\r\n"
                + "    at java.base/java.lang.reflect.Method.invoke("
                + "Method.java:566)\r\n"
                + "    at org.junit.runners.model."
                + "FrameworkMethod$1.runReflectiveCall"
                + "(FrameworkMethod.java:50)\r\n"
                + "    at org.junit.internal.runners."
                + "model.ReflectiveCallable.run"
                + "(ReflectiveCallable.java:12)\r\n"
                + "    at org.junit.runners.model."
                + "FrameworkMethod.invokeExplosively"
                + "(FrameworkMethod.java:47)\r\n"
                + "    at org.junit.internal.runners"
                + ".statements.InvokeMethod.evaluate"
                + "(InvokeMethod.java:17)\r\n"
                + "    at org.junit.internal.runners."
                + "statements.RunBefores.evaluate"
                + "(RunBefores.java:26)\r\n"
                + "    at org.junit.internal.runners"
                + ".statements.RunAfters.evaluate"
                + "(RunAfters.java:27)\r\n"
                + "    at student.testingsupport.junit4."
                + "RunTestMethodWrapper.evaluate"
                + "(RunTestMethodWrapper.java:74)\r\n"
                + "    at org.junit.internal.runners."
                + "statements.FailOnTimeout$CallableStatement.call"
                + "(FailOnTimeout.java:298)\r\n"
                + "    at org.junit.internal.runners."
                + "statements.FailOnTimeout$CallableStatement.call"
                + "(FailOnTimeout.java:292)\r\n"
                + "    at java.base/java.util.concurren"
                + "t.FutureTask.run(FutureTask.java:264)\r\n"
                + "    at java.base/java.lang.Thread.r"
                + "un(Thread.java:834)\r\n"
                + "Usage: java SemSearch <worldSize> "
                + "<commandFile>\r\n"
                + "Usage: java SemSearch <worldSize> "
                + "<commandFile>\r\n" + "",
            systemOut().getHistory());
    }
}
